version: 2
updates:

  -
    package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "Docker"
    directory: "/"
    schedule:
      interval: "daily"
