name: test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    -
      name: Run scam
      run: |
        docker run --rm -t -v $(pwd):/home/repo coinbase/salus
    -
      name: Run build
      run: |
        docker-compose build
    -

